GHA: Try to fail the build if notarization failed

diff --git a/.github/workflows/gh-hosted-eclipse-distro-build.yml b/.github/workflows/gh-hosted-eclipse-distro-build.yml
--- a/.github/workflows/gh-hosted-eclipse-distro-build.yml
+++ b/.github/workflows/gh-hosted-eclipse-distro-build.yml
@@ -266,8 +266,17 @@ jobs:
           do
             ${{ github.workspace }}/.github/scripts/notarize-osx-distro-file.sh $dmg_file $NOTARIZE_PROFILE &
           done
-          wait
-          echo "Done signing and notarization of DMG files"
+          for job in `jobs -p`
+          do
+            wait $job || let "FAIL+=1"
+          done
+          if [ "$FAIL" == "0" ];
+          then
+            echo "Done signing and notarization of DMG files"
+          else
+            echo "Failed Notarization"
+            exit 1
+          fi
       - name: Update DMG files on S3
         id: update-s3
         run: |
