[GHA] Try snapshot builds with older AWS CLI

diff --git a/.github/workflows/gh-hosted-eclipse-distro-build.yml b/.github/workflows/gh-hosted-eclipse-distro-build.yml
--- a/.github/workflows/gh-hosted-eclipse-distro-build.yml
+++ b/.github/workflows/gh-hosted-eclipse-distro-build.yml
@@ -41,6 +41,12 @@ jobs:
   eclipse-distro-build:
     runs-on: ubuntu-latest
     steps:
+      - name: Setup AWS CLI 2.22
+        run: |
+          curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
+          unzip -q awscliv2.zip
+          sudo ./aws/install --update
+          aws --version
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
         with:
           sparse-checkout: |
@@ -150,62 +156,73 @@ jobs:
       p2_path: ${{ steps.s3-paths.outputs.p2_path }}
       version: ${{ steps.project-version.outputs.version }}
 
-#  sign-win-distros:
-#    needs: [ eclipse-distro-build ]
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
-#        with:
-#          sparse-checkout: |
-#            .github
-#      - name: Download Win Zips from S3 for Signing
-#        run: |
-#          rm -f spring-tool-suite-4*win*.zip*
-#          rm -f spring-tool-suite-4*win*.self-extracting.jar*
-#          ls
-#          aws s3 mv s3://$AWS_S3_BUCKET/sts4-distro-ci-temp/${{ needs.eclipse-distro-build.outputs.id }} . --recursive --exclude "*" --include "spring-tool-suite-4*win*.zip*" --exclude "*/*" --no-progress
-#      - name: Sign EXE within zip files
-#        id: sign
-#        run: |
-#          files=`ls spring-tool-suite-4*win*.zip`
-#          for file in $files
-#          do
-#            ${{ github.workspace }}/.github/scripts/sign-exe-in-zip-file.sh $file ${{ github.workspace }}/.github/scripts/sign-exe.sh ${{ github.workspace }}/.github/scripts/self-extracting-jar-creator.jar ${{ github.run_id }} &
-#          done
-#          FAIL=0
-#          for job in `jobs -p`
-#          do
-#            wait $job || let "FAIL+=1"
-#          done
-#          if [ "$FAIL" == "0" ];
-#          then
-#            echo "Done signing EXE files"
-#          else
-#            echo "Failed signing one or more EXE files"
-#            exit 1
-#          fi
-#      - name: Update Win zip/jar on S3
-#        id: update-s3
-#        run: |
-#          dist_path=${{ needs.eclipse-distro-build.outputs.dist_path }}
-#          echo "Processing S3 update..."
-#          ls spring-tool-suite-4*win*
-#          echo "Removing old win zip and self extracting jar files from S3..."
-#          aws s3 rm s3://$AWS_S3_BUCKET/${dist_path} --recursive --exclude "*" --include "spring-tool-suite-4*win*.zip*" --include "spring-tool-suite-4*win*.self-extracting.jar*" --exclude "*/*"
-#          echo "Uploading new win zip and self extracting jar files to S3..."
-#          aws s3 mv . s3://$AWS_S3_BUCKET/${dist_path} --recursive --exclude "*" --include "spring-tool-suite-4*win*.zip*" --include "spring-tool-suite-4*win*.self-extracting.jar*" --exclude "*/*" --no-progress
-#      - name: Update Nightly Distro Downloads page
-#        if: ${{ inputs.build_type == 'snapshot' }}
-#        run: |
-#          dist_path=${{ needs.eclipse-distro-build.outputs.dist_path }}
-#          eclipse_profile=${{ inputs.eclipse_profile }}
-#          eclipse_version=${eclipse_profile:0:2}.${eclipse_profile:2}
-#          ${{ github.workspace }}/.github/scripts/update-distro-download-page.sh $dist_path $eclipse_version ${{ inputs.build_type }} $AWS_S3_BUCKET $DOWNLOAD_URL_ROOT
+  sign-win-distros:
+    needs: [ eclipse-distro-build ]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Setup AWS CLI 2.22
+        run: |
+          curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
+          unzip -q awscliv2.zip
+          sudo ./aws/install --update
+          aws --version
+      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
+        with:
+          sparse-checkout: |
+            .github
+      - name: Download Win Zips from S3 for Signing
+        run: |
+          rm -f spring-tool-suite-4*win*.zip*
+          rm -f spring-tool-suite-4*win*.self-extracting.jar*
+          ls
+          aws s3 mv s3://$AWS_S3_BUCKET/sts4-distro-ci-temp/${{ needs.eclipse-distro-build.outputs.id }} . --recursive --exclude "*" --include "spring-tool-suite-4*win*.zip*" --exclude "*/*" --no-progress
+      - name: Sign EXE within zip files
+        id: sign
+        run: |
+          files=`ls spring-tool-suite-4*win*.zip`
+          for file in $files
+          do
+            ${{ github.workspace }}/.github/scripts/sign-exe-in-zip-file.sh $file ${{ github.workspace }}/.github/scripts/sign-exe.sh ${{ github.workspace }}/.github/scripts/self-extracting-jar-creator.jar ${{ github.run_id }} &
+          done
+          FAIL=0
+          for job in `jobs -p`
+          do
+            wait $job || let "FAIL+=1"
+          done
+          if [ "$FAIL" == "0" ];
+          then
+            echo "Done signing EXE files"
+          else
+            echo "Failed signing one or more EXE files"
+            exit 1
+          fi
+      - name: Update Win zip/jar on S3
+        id: update-s3
+        run: |
+          dist_path=${{ needs.eclipse-distro-build.outputs.dist_path }}
+          echo "Processing S3 update..."
+          ls spring-tool-suite-4*win*
+          echo "Removing old win zip and self extracting jar files from S3..."
+          aws s3 rm s3://$AWS_S3_BUCKET/${dist_path} --recursive --exclude "*" --include "spring-tool-suite-4*win*.zip*" --include "spring-tool-suite-4*win*.self-extracting.jar*" --exclude "*/*"
+          echo "Uploading new win zip and self extracting jar files to S3..."
+          aws s3 mv . s3://$AWS_S3_BUCKET/${dist_path} --recursive --exclude "*" --include "spring-tool-suite-4*win*.zip*" --include "spring-tool-suite-4*win*.self-extracting.jar*" --exclude "*/*" --no-progress
+      - name: Update Nightly Distro Downloads page
+        if: ${{ inputs.build_type == 'snapshot' }}
+        run: |
+          dist_path=${{ needs.eclipse-distro-build.outputs.dist_path }}
+          eclipse_profile=${{ inputs.eclipse_profile }}
+          eclipse_version=${eclipse_profile:0:2}.${eclipse_profile:2}
+          ${{ github.workspace }}/.github/scripts/update-distro-download-page.sh $dist_path $eclipse_version ${{ inputs.build_type }} $AWS_S3_BUCKET $DOWNLOAD_URL_ROOT
 
   sign-osx-distros:
     needs: [ eclipse-distro-build ]
     runs-on: macos-15
     steps:
+      - name: Setup AWS CLI 2.22
+        run: |
+          curl -s "https://awscli.amazonaws.com/AWSCLIV2-2.22.35.pkg" -o "awscliv2.pkg"
+          sudo installer -pkg ./awscliv2.pkg -target /
+          aws --version
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
         with:
           sparse-checkout: |
@@ -295,11 +312,16 @@ jobs:
           rm -rf *spring-tool-suite-4*macosx*
 
   purge_cache:
-#    needs: [ eclipse-distro-build, sign-win-distros, sign-osx-distros ]
-    needs: [ eclipse-distro-build, sign-osx-distros ]
+    needs: [ eclipse-distro-build, sign-win-distros, sign-osx-distros ]
     if: ${{ always() && inputs.build_type != 'snapshot' && contains(join(needs.*.result, ','), 'success')}}
     runs-on: ubuntu-latest
     steps:
+      - name: Setup AWS CLI 2.22
+        run: |
+          curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
+          unzip -q awscliv2.zip
+          sudo ./aws/install --update
+          aws --version
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
         with:
           sparse-checkout: |
@@ -389,11 +411,16 @@ jobs:
           }"          
 
   cleanup:
-#    needs: [ eclipse-distro-build, sign-win-distros, sign-osx-distros ]
-    needs: [ eclipse-distro-build, sign-osx-distros ]
+    needs: [ eclipse-distro-build, sign-win-distros, sign-osx-distros ]
     if: ${{ always() }}
     runs-on: ubuntu-latest
     steps:
+      - name: Setup AWS CLI 2.22
+        run: |
+          curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
+          unzip -q awscliv2.zip
+          sudo ./aws/install --update
+          aws --version
       - name: Remove Temp Build Artifacts from S3
         id: cleanup-s3-temp-storage
         run: |
